### ISSUE TITLE
Window manager theme doesn't change to rounded dark.

### ISSUE THREAD

**Issue by default0r** [jeffinshadow/dotfiles#1]
This , I know, will probably be a very dumb issue ; So i installed the materia kde theme , after that placed the dot files in the .local/share directory and followed the steps in the same order , since I didn't get the rounded edges I rebooted too , but nothing still.

I'm running Arch with latest updates in Kde.

Thanks for your time.

**Comment by jeffinshadow** [comment]
The "my themes" section in the readme acts as a dependency guide for the "theme pack". To have rounded corners in window decoration, you will need to install Sierra-Breeze-Enhanced and after applying it as a window decoration, go to his confirmations and set the corners to your liking.

**Comment by default0r** [comment]
THANKS!
